import React, { useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { AppBar } from '../../components/AppBar';
import { Button } from '../../components/Button';
import { Card } from '../../components/Card';
import { Screen } from '../../components/Screen';
import { askMediScanHelpdesk } from '../../services/qvacMedicineAI';
import { useTheme } from '../../theme/ThemeProvider';
import { HelpdeskAnswer } from '../../types/Medicine';
import { StackProps } from '../_shared/ScreenStub';

export function HelpdeskScreen({ navigation }: StackProps<'Helpdesk'>) {
  const { colors, fonts, fontSizes, radius, spacing } = useTheme();
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<HelpdeskAnswer | null>(null);
  const [loading, setLoading] = useState(false);

  async function submit() {
    const trimmed = question.trim();
    if (!trimmed) return;

    setLoading(true);
    try {
      const next = await askMediScanHelpdesk(trimmed);
      setAnswer(next);
    } finally {
      setLoading(false);
    }
  }

  return (
    <Screen>
      <AppBar title="QVAC Helpdesk" showBack onBack={() => navigation.goBack()} />

      <Card>
        <Text style={{ fontFamily: fonts.displayMedium, fontSize: fontSizes.lg, color: colors.text }}>
          QVAC Medicine Helpdesk
        </Text>
        <Text
          style={{
            fontFamily: fonts.body,
            fontSize: fontSizes.sm,
            color: colors.textMuted,
            marginTop: spacing.sm,
          }}
        >
          Ask about a medicine name, use, warning, or side effect. The answer is grounded on the local
          medicine database and should not be used as a prescription.
        </Text>
        <TextInput
          multiline
          value={question}
          onChangeText={setQuestion}
          placeholder="Example: Is paracetamol for fever? What are ibuprofen warnings?"
          placeholderTextColor={colors.textMuted}
          textAlignVertical="top"
          style={{
            marginTop: spacing.md,
            minHeight: 90,
            backgroundColor: colors.paper,
            borderRadius: radius.md,
            padding: spacing.md,
            borderWidth: 1,
            borderColor: colors.border,
            fontFamily: fonts.body,
            fontSize: fontSizes.base,
            color: colors.text,
          }}
        />
        <View style={{ marginTop: spacing.md }}>
          <Button
            title={loading ? 'Asking QVAC AI…' : 'Ask Helpdesk'}
            onPress={submit}
            loading={loading}
            disabled={loading || !question.trim()}
          />
        </View>
      </Card>

      {answer ? (
        <Card style={{ backgroundColor: colors.brandLight }}>
          <Text style={{ fontFamily: fonts.displayMedium, fontSize: fontSizes.md, color: colors.text }}>
            Answer
          </Text>
          <Text
            style={{
              fontFamily: fonts.body,
              fontSize: fontSizes.base,
              color: colors.text,
              marginTop: spacing.sm,
            }}
          >
            {answer.answer}
          </Text>
          <Text
            style={{
              fontFamily: fonts.bodySemibold,
              fontSize: fontSizes.sm,
              color: colors.danger,
              marginTop: spacing.md,
            }}
          >
            {answer.safety}
          </Text>
          <Text
            style={{
              fontFamily: fonts.body,
              fontSize: fontSizes.sm,
              color: colors.textMuted,
              marginTop: spacing.sm,
            }}
          >
            Generated by: {answer.generatedBy}
          </Text>
        </Card>
      ) : null}

      {answer?.sources?.length ? (
        <Card>
          <Text style={{ fontFamily: fonts.displayMedium, fontSize: fontSizes.md, color: colors.text }}>
            Local sources used
          </Text>
          {answer.sources.map((source, index) => (
            <Text
              key={`${source}-${index}`}
              style={{
                fontFamily: fonts.body,
                fontSize: fontSizes.sm,
                color: colors.textMuted,
                marginTop: spacing.xs,
              }}
            >
              • {source}
            </Text>
          ))}
        </Card>
      ) : null}
    </Screen>
  );
}
